# Site settings
title: Alexandre Pofelski
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://slimpotatoes.github.io"
domain: "slimpotatoes.github.io"

# User settings
username: Alexandre Pofelski
user_description: It's me.
user_title: Post doctorate researcher in Transmission Electron Microscopy
email: alexandre.pofelski@gmail.com
twitter_username: APofelski
linkedin_username: alexandre-pofelski-120a5a13
github_username:  slimpotatoes

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude: ['package.json', 'src' , 'node_modules']
